name: pacha_biometric_example
description: A simple example demonstrating the pacha_biometric plugin.
publish_to: 'none'  # Empêche la publication de l'exemple sur pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pacha_biometric:
    path: ../  # Pointe vers le plugin parent dans le répertoire supérieur

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true